local km = require("package.keymaps")

return {
	"dlyongemallo/diffview-plus.nvim",
	main = "diffview",
	lazy = true,
	opts = function()
		local actions = require("diffview.config").actions

		return {
			keymaps = {
				view = {
					{ "n", "<tab>", actions.select_next_entry, { desc = km.desc("Diffview: open next file") } },
					{ "n", "<s-tab>", actions.select_prev_entry, { desc = km.desc("Diffview: open previous file") } },
					{ "n", "<leader>te", actions.toggle_files, { desc = km.desc("Diffview: toggle file panel") } },
					{ "n", "<leader>tg", actions.focus_files, { desc = km.desc("Diffview: focus file panel") } },

					{ "n", "<leader>b", false },
					{ "n", "<leader>e", false },
					{ "n", "[F", false },
					{ "n", "]F", false },
					{ "n", "gf", false },
					{ "n", "g<C-x>", false },
					{ "n", "<C-w><C-f>", false },
					{ "n", "<C-w>gf", false },
					{ "n", "gx", false },
					{ "n", "<C-w>T", false },
				},
				file_panel = {
					{ "n", "j", actions.next_entry, { desc = km.desc("Diffview: cursor to next entry") } },
					{ "n", "<down>", actions.next_entry, { desc = km.desc("Diffview: cursor to next entry") } },
					{ "n", "k", actions.prev_entry, { desc = km.desc("Diffview: cursor to previous entry") } },
					{ "n", "<up>", actions.prev_entry, { desc = km.desc("Diffview: cursor to previous entry") } },
					{ "n", "<cr>", actions.select_entry, { desc = km.desc("Diffview: open diff for entry") } },
					{ "n", "<leader>te", actions.toggle_files, { desc = km.desc("Diffview: toggle file panel") } },
					{ "n", "<leader>tg", actions.focus_files, { desc = km.desc("Diffview: focus file panel") } },
					{ "n", "g?", actions.help("file_panel"), { desc = km.desc("Diffview: open help panel") } },

					{ { "n", "x" }, "w", false },
					{ "n", "C", false },
					{ "n", "H", false },
					{ "n", "zo", false },
					{ "n", "h", false },
					{ "n", "zc", false },
					{ "n", "za", false },
					{ "n", "zR", false },
					{ "n", "zM", false },
					{ "n", "<c-b>", false },
					{ "n", "<c-f>", false },
					{ "n", "<tab>", false },
					{ "n", "<s-tab>", false },
					{ "n", "i", false },
					{ "n", "R", false },
					{ "n", "o", false },
					{ "n", "l", false },
					{ "n", "<2-LeftMouse>", false },
					{ "n", "[F", false },
					{ "n", "]F", false },
					{ "n", "gf", false },
					{ "n", "g<C-x>", false },
					{ "n", "-", false },
					{ "n", "s", false },
					{ "n", "S", false },
					{ "n", "U", false },
					{ "n", "X", false },
					{ "n", "L", false },
					{ "n", "gL", false },
					{ "n", "f", false },
					{ "n", "[x", false },
					{ "n", "]x", false },
					{ "n", "<leader>cO", false },
					{ "n", "<leader>cT", false },
					{ "n", "<leader>cB", false },
					{ "n", "<leader>cA", false },
					{ "n", "dX", false },
					{ "n", "<leader>b", false },
					{ "n", "<leader>e", false },
					{ "n", "<C-w><C-f>", false },
					{ "n", "<C-w>gf", false },
					{ "n", "gx", false },
					{ "n", "<C-w>T", false },
				},
			},
		}
	end,
}
